### ISSUE TITLE
[How To] disable craft on a region/ arena ?

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#105]
I have a game with chest and stuff. Players can build, destroy but they must no craft pickaxe. 

How prevent craft please ?

**Comment by Oruss7** [comment]
Not implemented ='(

**Comment by slipcor** [comment]
INVENTORY is not okay, right? It prevents people from clicking in the inventory menu.

If not, I will add a CRAFT region protection :)

https://github.com/slipcor/pvparena/blob/master/src/net/slipcor/pvparena/loadables/ArenaRegion.java#L104

**Comment by Oruss7** [comment]
It's a game where you can destroy and place blocks. But people craft pickaxes and ladders ...

**Comment by slipcor** [comment]
okay, I am almost done :) I have to go shopping now, but you will get a test build today!

**Comment by Oruss7** [comment]
You're amazing, thanks !
Have good chrismas

**Comment by slipcor** [comment]
you too !

http://pa.slipcor.net/pvparena.jar is to test - I hope it works :D

**Comment by Oruss7** [comment]
Okay I try

**Comment by Oruss7** [comment]
seems not work. How you save protections on the yml file ? I have only ```  test: labo,16,1,-17,25,8,-9,cuboid,0,5054,BATTLE```

**Comment by slipcor** [comment]
hah well that's hard to explain, it's easier to check with the region protection command:

/pa [arena] regions test

it debugs the region setup and shows all set protections. does it contain CRAFT ? if not:

/pa [arena] regionflag test CRAFT true

That should set it to protected

**Comment by Oruss7** [comment]
```/pa [arena] regionflag test CRAFT true```  is the command for NoCAMP, DEATH ...
I have check my region, i have CRAFT.

Why save is hard to explain? I'm curious now

**Comment by slipcor** [comment]
because 5054 is a bitmask. The protection values are numbered and the value you see is a sum of "2 to the power of number" - in your case

5054 = binary "1001110111110" - all those 1s are "set" protection values, but I don't remember the order, but I only know the LAST added (the leftmost) is CRAFT, and it is a 1 :D so it is set and should work.

However, it's hard to do the calculation in the head, especially if you don't know the order of the things :D

Okay, I will look into why this doesnt work!

**Comment by slipcor** [comment]
I just verified it works, but ... maybe I had to restart the server for the protection to take effect? I am not sure, I added debugging and it showed one thing!

OPs (or people having the rights to admin an arena, or THAT arena) can always craft :P sooo if you tested with an OP account, thats probably why it didnt protect :) for normal players it SHOULD work

**Comment by Oruss7** [comment]
Ahh, sorry, I had OP. That's work without. Is this build stable for production server ?

**Comment by slipcor** [comment]
I hope so. I have no way of testing this tbh, I have no server, no players :/ I did not change that much though - btw I just fixed another NPE issue that happens every now and then, I recommend you using this version :dancer: 
v1.3.0.554 - fix an NPE in some places due to a return value of null should be expected!

**Comment by Oruss7** [comment]
It's my friend server, i will talk to him about this. Thanks for your support.

**Comment by slipcor** [comment]
You're welcome :) thanks for staying with me :D

**Comment by Oruss7** [comment]
My friend is okay, You know him, he has done the french translation =)

**Comment by slipcor** [comment]
cool :D

**Comment by Oruss7** [comment]
``` v1.3.0.554 - fix an NPE in some places due to a return value of null should be expected! ```
Have a jar or i need build it myself ?

**Comment by slipcor** [comment]
http://pa.slipcor.net/pvparena.jar

**Comment by Oruss7** [comment]
Can you re-open your jenkins to test your dev versions please ?
