### ISSUE TITLE
[Bug] 'Rounds' bugs.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#149]
Configuration display.

```
rounds:
- net.slipcor.pvparena.goals.GoalPlayerLives@5e91ca1d
- net.slipcor.pvparena.goals.GoalPlayerLives@ca55248
- net.slipcor.pvparena.goals.GoalPlayerLives@25e72012
```

---

Vault reward isn't being handed out to winner at the end of each round. Instead, only the winner of the last round gets the win reward.

---

Started game. Killed myself on round one. Everyone got killed except one person. I left the arena before round 2 started. Round 2 did not start.

http://paste.ubuntu.com/15152766/

---

Player who left the arena during a second round got teleported back into the arena when a third round started.

---

Game got to round 2. Players were killing themselves and not running out of lives. Just respawning at a spawn point.

http://paste.ubuntu.com/15152735/

**Comment by slipcor** [comment]
apparently we need to push this to either MC 1.9 or PA v2.0 - in order to fix this I have to create a certain state that can receive item rewards - and a state that basically is not part of the arena (to be reset safely properly) but still "accessible" for the next arena round.

What about the next round anyways? Who should be added? Ppl who have left were added, people who won stay in the arena, but the rest.... not so much.

I cannot fully reset the arena because then the start event would break because of no player being part of the arena. So what... can we do? :D

**Comment by mibby** [comment]
Closing ticket. I personally no longer use this module so closing to reduce the possible work burden to implement / fix. Feel free to re-open if this is something you do want to implement.

Rounds was quite buggy but it's been years. It would probably be better to consider implementing as a core function in any type of rewrite so you could have games with rounds that switch gamemodes or flip sides.
