### ISSUE TITLE
Remove default offset set in the config.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#166]
https://github.com/slipcor/pvparena/blob/master/src/config.yml#L8

Should probably remove the X and Z offset set in the main config by default, as it makes all spawns off-centered. The Y offset is the only important setting - used to fix falling/being inside a block. For more spawn refinement, people should just use the tp offsets feature added recently.

**Comment by slipcor** [comment]
No :) we had this discussion and I hoped it was over xD

I added this config specifically for you (to set it to 0.0) because you want precise spawns and noone ever has complained about this "offset" that I have been doing for ages now (secretly :P). People set  a spawn somewhere and I always set the spawn in the very middle of that block, that is how I implemented it from the beginning, with a hardcoded offset X and Z :)

And yes, another offset Y to make sure ppl don't fall through the floor (too much)

**Comment by mibby** [comment]
Depy collision. Can ignore the ticket.
