### ISSUE TITLE
forcewin : lose inventory

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#173]
The title said all. 

When we use forcewin, losers die and retrieve their inventory, then the game end and they lose their inventory (bad synchronization ?)

**Comment by slipcor** [comment]
can you please double check that this is not related to the other bug you reported that had inventories in it? I literally do the same as the redstone module does, did you test that and it worked? :P it has been some time since I tested that :D

But I just did, and it worked on my server :/ could it be an inventory issue because of world change?

**Comment by Oruss7** [comment]
Sorry i havn't tested, lot of work at the end of school year ^^'

**Comment by Oruss7** [comment]
Confirmed When Thor kill losers, they respawn on EXIT with full inventory, then cooldown for the end 3,  2, 1 ... then losers are againt teleported to EXIT without inventory. 


full arena config used to test : 

http://pastebin.com/M8sKvWHH

pa version: 1.3.2.105

**Comment by slipcor** [comment]
Okay well I can no longer remember ( I could not back then taht's why I didnt mention a number ) which ticket it was - can you try setting resetDelay to 1 ? Maybe thats fixes some things :D

**Comment by Oruss7** [comment]
Can't reproduce.

**Comment by Oruss7** [comment]
Still lose my inventory. 1.3.2.128

**Comment by slipcor** [comment]
can you please do a debug, @Oruss7 ? :/

**Comment by Oruss7** [comment]
Sorry, can't reproduced this bug on PA 1.3.2.155 (1.9 version)
