### ISSUE TITLE
Spectator teleport to their spawn and escape immediately when use /pa spectate

### ISSUE THREAD

**Issue by webrsb** [slipcor/pvparena#175]
Use module: flyspectate
I have two types of region WATCH and BATTLE. A player isn't in the WATCH region then using command /pa spectate. The player will teleport to spawn of WATCH region and showing "You escaped the battlefield. Goodbye!". In addition, player will switch to CREATEIVE mode. It is no issue if player in the WATCH region. The player has not been teleport to WATCH region and [this] (https://github.com/slipcor/pvparena/blob/master/src/net/slipcor/pvparena/loadables/ArenaRegion.java#L644) check immediately cause this issue.

**Comment by slipcor** [comment]
Thanks for reporting this and linking me to my code :) Strange how never had that error before. Fix incoming!

**Comment by webrsb** [comment]
The problem still exists. This video can explain how bug generate: https://youtu.be/h2Na98_jUpA

**Comment by slipcor** [comment]
oh I didnt want to close it. can you verify, @webrsb ??

**Comment by webrsb** [comment]
Thanks for your hard work. I will take a look in three day.

**Comment by slipcor** [comment]
don't worry! thanks to your debugging video I was able to find the specific reason for this to happen!

- and it still happens on v103! -

It only happens because you join FROM THE LOUNGE :D

Do you really have to? I will try to fix it nevertheless. Again, build #103 will NOT fix this!

**Comment by slipcor** [comment]
Alright. thanks for the effort in trying to find the piece of code, it was not really what you thought but rather 2 things together:

1) the teleport to the arena / spectator is delayed by 3 ticks. It can happen (it didnt every time for me) that you JUST hit the LOUNGE timer, so that:
2) when standing in a lounge region, you get kicked out of that lounge unless you are not playing at all (before doing the command) or you are in "LOUNGE" status (after the command, but you are WATCH status!!)

So I fixed this by introducing an intermediary variable that shows everyone that the player is "being teleported" - I hope this does not break (to stay true for example) as it basically excempts players from being kicked out of the arena / being kicked when leaving the battlefield etc.

However you need the latest modules, too:

https://ci2.craftyn.com/job/PVP%20Arena%20Modules/

So those ^ (FlySpectate and RealSpectate were fxed by this), and the main plugin version #103 !
