### ISSUE TITLE
Players TP'd to arena coordinates in return world

### ISSUE THREAD

**Issue by ChrisLane** [slipcor/pvparena#214]
Version: This issue exists on many versions from Jenkins all with up to date modules as well as a version compiled by myself to ensure 1.7.10 compatibility https://github.com/ChrisLane/pvparena.

Gamemode: All (ffa, tdm, ctf)

Modules: Announcements, ColorTeams, EventActions, SpecialJoin

---

I've had the problem on my server for a while now that players are sometimes teleported to the wrong place after the end of an arena and end up dying.

It seems that the plugin teleports players back to the world that they joined from but instead of teleporting players to their original coordinates, it teleports them to coordinates from the arena.

Here is a log of an arena when this happened: http://paste2.org/ns3L6hy9

We can see that the player 'DaKommunist' is teleported to the wrong coordinates.
Line 7261:
"Location{world=CraftWorld{name=world},x=-122.49211388493582,y=156.0,z=-120.95919592231635,pitch=6.90718,yaw=-83.72518}"

These coordinates are claimed to be for the world "world" but actually are from the position in the world "games".

**Comment by slipcor** [comment]
Can this by any chance be caused by the world management plugin? PVP Arena does not alter the world while caring about a teleport, and it physically debugs ALL teleport events as you see it right there, and it would tell us if it cancelled or altered the destination.

I actually never CHANGE the destination, I only ever cancel the teleport, ubt then I add stuff containing "cancelling" and the reason to the debug :/

I have never heard of this issue and that makes me think it is something on your end. Maybe, if you're unlucky, some bad plugin caring about teleport events?

Can you set a side some people for a debug plugin I could compile? It would spam every teleport event at every stage and every "caring" plugin (and in your case the destination, to see when it breaks)

**Comment by ChrisLane** [comment]
I'm open to any debug options really. I haven't tried testing it without other plugins because the issue often doesn't occur for me.

Perfectly happy to use a spammy debug plugin :smile: 
Thanks

**Comment by ChrisLane** [comment]
Having said that I'm doing some debugging of my own, I think one of our plugins might have some inverted logic for ignoring worlds.

**Comment by slipcor** [comment]
@ChrisLane http://pa.slipcor.net/ECD-TP.jar

1) install the plugin, it will generate a config
2) set enabled: true
3) set debug-listener: console

Because with all the stuff going on no player will be able to read all what's going on. It will output:

`
        msg[0] = "-------------------------";
        msg[1] = event.getEventName(); // should be PlayerTeleportEvent
		msg[2] = "prio: " + prio.name(); // the priority
		msg[3] = "cancelled: " + (cancelled?"yes":"no");
		msg[4] = "plugins: "; // the plugins listening to the event at this priority
		msg[5] = "destination: " + event.getTo();` // the destination location

**Comment by ChrisLane** [comment]
Testing this today.

**Comment by ChrisLane** [comment]
@slipcor Error with the ECD plugin.

NPE http://paste2.org/s2FfEWIL
Also, a reload config command would be great if that's a quick add.
