### ISSUE TITLE
Players get "Arena is diabled" error when trying to join, even when its enabled

### ISSUE THREAD

**Issue by robotnikthingy** [slipcor/pvparena#243]
Using Spigot 1.10.2
Using latest version of PVP Arena

When a player tries to join the arena, they get a message saying the arena is disabled, even though I enabled it. When I join, it works fine though, and I know they have the permissions to join.

Also they are trying to join using signs. I am using the SpecialJoin mod to do that

**Comment by robotnikthingy** [comment]
anyone?
If you need me to provide any more info just let me know

**Comment by slipcor** [comment]
How many arenas do you have? Are all of them enabled?

If the first answer is "1" or the second answer is "yes", then please do the following:

/pa debug all
try to join with the sign
/pa debug off

and www.pastebin.com the contents of /pvparena/debug/*.log

If you have more than 1 arena, double check the spelling of your arena, and that your arenas are not named too similarly.

it might be that the name check is catching the disabled arena because the name fits better than the one that you want to have.

Also, please do not say "latest" - which latest, from spigot? from the jenkins? Please share the exact version string so I know where to look ;)

**Comment by robotnikthingy** [comment]
Actually it seems to have fixed itself after a server restart and setting up the join signs again, since they didnt even work after the restart. I tested it using the permissions of a regular user and it seems to work

**Comment by slipcor** [comment]
Yeah sure, if it does not work, have them try with debug activated :) Then I can see where it messes up!

**Comment by robotnikthingy** [comment]
yep it seems like the problem solved itself after a server restart!
