### ISSUE TITLE
OP's keep their class gear when leaving

### ISSUE THREAD

**Issue by Sikatsu** [slipcor/pvparena#247]
When I join the PvP Arena (FreeForAll) as an OP and I leave the match, I will keep the gear from that class.

Is this a bug or is there a setting to fix this matter? Normal players don't have this.

I'd really like to solve this, as it resets my inventory due to it.

**Comment by Oruss7** [comment]
I'm op and never had this issue. have you config the class gear before enter arena?

**Comment by Sikatsu** [comment]
Yes I changed the class gear. Might it be a setting? Or because of gameworldinventories? Seems to happen when i'm in creative..

**Comment by slipcor** [comment]
oh yeah most certainly it has to do with the inventory handling plugin. Somehow it stored the arena gear when you changed worlds before. As only OPs and creative are affected it should not be as big of an issue right?

To fix this, /pa [arena] set range 99999999

This only allows to join from the same world (and not from a creative world)

**Comment by Sikatsu** [comment]
Well I made sure to disable joining the pvp arena while in Creative, however for staff it is kinda irritating tho. Hoped there was some sort of fix, custom items and such are lost now :(

**Comment by slipcor** [comment]
yeah sadly there is nothing I can do there now :/ sorry!

**Comment by Sikatsu** [comment]
Alright, may be closed. Switched to PerWorldInventory.

**Comment by Oruss7** [comment]
Warning with perWorldInventory. This plugin is slow and bugs occurs when switching too fast (player crashing or switching quickly)

**Comment by Sikatsu** [comment]
Switching gamemode or world? I do know theres an issue with switching gamemode, not sure if it applies to world switching aswell. I couldn't find a better solution

**Comment by slipcor** [comment]
All those inventory plugins cause so many issues. I don't know what to do about it, I cannot constantly keep track of peopless stuff and force put it in there all day :P

If this does not get fixed by them you have to restrict the world change by setting "range" to 99999999

So that they can only ever join from the same world and HOPEFULLY the inventory plugin does not mess that up

**Comment by Sikatsu** [comment]
I got no issues with PerWorldInventory :)

**Comment by slipcor** [comment]
Well all I can say is that it does not happen in vanilla gameplay, and I do my best to fix everything by literally waiting before doing a teleport and an inventory reset, there is not much I can do apart from that. If things still mess up you have to restrict people from joining the arena.

And well this might not work well on OPs because they have all perms, most of the time. I feel like you have to fix this on your end :/
