### ISSUE TITLE
Able to drink / use potions in the arena lounge.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#263]
PVPArena dev 222

You are able to drink bottle potions in the arena lounge. It grants you the potion effect for the listed duration. 

As well as admins are able to throw splash and lingering potions in the lounge. The potion effect does not go off but it uses the potion quantity in your inventory. Admins are not able to use a bow and arrow in the lounge.

Shouldn't both be cancelled while in the lounge?

**Comment by slipcor** [comment]
True. Debug plz? :P

**Comment by mibby** [comment]
@slipcor 
PA 1.3.4.252

You are no longer able to drink potions with https://github.com/slipcor/pvparena/commit/c1fb228a53b3fd81ac52a51547c713e6e47dc664 and splash/lingering potions are cancelled when right clicked against a block. However, splash and lingering potion count still goes down when right clicking in the air. It doesn't throw the potion but it disappears from your lounge inventory.

Debug of me throwing the splash / lingering potions in my inventory, in the lounge.
http://paste.ubuntu.com/24182086/

**Comment by slipcor** [comment]
Throwing items [clicking in the air] is officially a "cancelled interaction event" - when your logic relies on that to be not cancelled, you get confused.

Good job, Bukkit.

Fixed by enforcing the cancellation....
Yeah why does that make a difference you ask?

"if (isCancelled()) .setCancelled(true)" does actually break things and change things. I don't even bother sending in this bug. Fixed in the plugin.
