### ISSUE TITLE
PVPArena micro-optimization investigation.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#300]
>A) BattleRunnable - do we need all instances? Can we disable them via config? Can we improve how they work?
B) EndRunnable - can we improve this in any way without breaking player restoring obviously?

**Comment by slipcor** [comment]
I think I have bad news.

BattleRunnable literally is only ever used in the BattleFieldGuard module, per definition it has to check for each player anyways so I cannot really change much about it, and it is double checking that it does not instanciate twice so... I am not sure what to optimize... Disabling this is done via removing BattleFieldGuard so there is nothing we can or should do...

EndRunnable is used in many places, but the instanciation also always checks so that there is only ONE endrunnable, and, yeah, the resetting is intense and can probably not be fixed, at least not in the realm of the end runnable. maybe in the resetting method :/

**Comment by mibby** [comment]
@slipcor For reference. https://timings.aikar.co/?id=06f9ca49da8d47e3929864e1a116edab#plugins

**Comment by slipcor** [comment]
Explanation needed :P

**Comment by mibby** [comment]
Just specific pvparena events showing up as the laggiest plugin events (not that laggy, just at the top of the tick stack) on my server at the time. :P For reference so any v2.0 rewrites can be looked at with performance optimizations in mind.
