### ISSUE TITLE
Spectate: not working

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#304]
- Player are not in spectator gamemode
- Player can leave the watch region without been kicked

COnfig:
https://pastebin.com/jWUR5HqY

Thanks

**Comment by slipcor** [comment]
Is the game runnig when this happens?

**Comment by slipcor** [comment]
One thing is for sure @Oruss7 your config - if the one linked is your config - is not loaded properly anyways - the line with "- ungod" is wrongly indented and thus it should not even work at all xD

**Comment by slipcor** [comment]
So if this is only an issue that happened when pasting - I need the same as in the other ticket, a full debug of when the spectator joins the game. Two things:

* when the game is not running, the range check is not active
* I just tried it with latest plugin and module versions, I got put into spectator mode fine
* I can not start the game to test this because you need three people for it :)
