### ISSUE TITLE
[question] Is the region system your version of Worldguard?

### ISSUE THREAD

**Issue by FrozenBeard** [slipcor/pvparena#307]
Im trying to wrap my head around the need for the region system in here, is it primarily just to replace worldguard?

/pa shipbattle !rt shipbattleregion BATTLE 
Means I can no longer edit/break blocks... 

Is it required I use your region system to play games? I would much prefer to use worldguard, its much much more powerful. 

Its difficult to understand as the documentation is really lacking detail.
Also why did you use files in github for the docs when Github has a built in Wiki...

**Comment by slipcor** [comment]
It is primarily there to prevent people breaking the arena, so, yes, for people who do not use worldguard :) I am not aiming to replace worldguard in that sense ;)

No, it is no requirement, however it adds to the security if you have no other means to secure it  - this applies to block breaking and people entering or leaving the battlefield - if you do not need that, feel free to not use regions at all!

Go ahead and remove the region /pa [arena] region remove shipbattleregion (I think)

Yeah the thing is that I as the developer really suck at seeing what is hard to understand for other people, I am literally coming from the code so everything is obvious to me.

I used files in github to have at least something - someone simply created them for me and I went with it because it still is better than not having any documentation, I'd say. Maybe some day I have time to create / maintain the wiki.

Thanks for the input!

**Comment by FrozenBeard** [comment]
Thank you so much for this plugin and your reply!
Ive spent all morning trying to figure this plugin out, It took me 30 mins to find out there was "mods" as its called enhancements in the wiki pages! I thought that was like enhancements for weapons etc, I randomly clicked on it and was like OH theres mods! May I suggest you move all your docs to the real Wiki, then people can edit it much easier than having to clone the repo and push changes! A better name would be Add-ons, People understand that its an additional extra to the plugin then.

Im glad I can use WG, im much more comfortable with it!

is there a way to run a command when the game ends?

**Comment by slipcor** [comment]
in a very complicated way, yes. There is a module "EventActions" which allows you to run commands on special events :)

Yeah I will look into getting a wiki started :O

**Comment by FrozenBeard** [comment]
This is brilliant. took me a while to figure out I needed to download the files.zip and add them into the files directory and then activate as needed, I figured out I needed SpecialJoin to create Join signs, which is awesome, But I cant figure out how to create leave/exit signs for the lobbys.

- How do I create a leave/exit sign for Lobbys?
- I see there is a temporary permissions Addon, Is there a way to just set a players group/rank instead? So when they pick a Class a command is run, then I could set /lp user <username> parent set ClassRankName. 
This way I have my permissions system dealing with all permissons instead of separating it into this weird addon for a plugin...Much easier to manage and update then.

**Comment by FrozenBeard** [comment]
idea: if its not possible that event actions just needs a new event for when a player picks a class, then we can run a command!

**Comment by slipcor** [comment]
there is nothing like a leave sign :/

the temporary permission node is given when the match has started, and it only supports what the basic bukkitperms supports, which is permission nodes :/

hmm changing a class could be added, it is not doing anything right now, I could try to add this later today ;)

**Comment by slipcor** [comment]
with the latest dev of modules [EventActions, obviously :P] it should work. The main plugin update is just for documentary reasons, no need to update the main plugin :)

**Comment by FrozenBeard** [comment]
Awesome, where do I find the dev of modules?

**Comment by slipcor** [comment]
Here :) https://ci2.craftyn.com/job/PVP%20Arena%20Modules/
