### ISSUE TITLE
[bug] Class save does not save shield data.

### ISSUE THREAD

**Issue by FrozenBeard** [slipcor/pvparena#315]
With a lot of themed arenas, people want themed shields, in my case, Pirates and the british. But the shield data is not saved! can we please get this data saved.

**Comment by slipcor** [comment]
Yeah I think back when I tried last time the banner and shield meta are not the same, and only one was implemented. I suggest you use class chests, because then minecraft hands out the items internally without me messing up things :) This will alleviate all possible issues PA might get with new items/unsupported subitems in the future

https://github.com/slipcor/pvparena/blob/master/doc/commands/classchest.md

Set up a class chest, you have the chest full of things, and the 4 to last items will be the armor [I think in the wrong order?] and the fifth to last time will be the shield/offhand slot :)

**Comment by FrozenBeard** [comment]
1. is a class chest a physical chest?
2. Does a class chest go in the lobby or in the main arena?
3. Is it a chest per person? What happens if someone takes items out and then theres none for the other players?
4. is the class chest just PER class? or can anyone raid it?

**Comment by slipcor** [comment]
1. yes it is a physical chest that is not secured, so put it in a place not accessible to players or outsiders
2. as I just said, because it's not secured, it can be anywhere, but I suggest placing it "in the same world" at least
3. no, this chest is a place that is simply read, and the items are copied 1:1 from chest to each player selectin this class
4. yes, as in 1./2. it is one set of items read from chests - you CAN define multiple classes to use the same chest, though, this will work
