### ISSUE TITLE
[Bug] Custom class can empty a whole inventory

### ISSUE THREAD

**Issue by Zughy** [slipcor/pvparena#326]
Let's say I have this map with a custom class sign. I click it and in 3 secs I receive the class. Good.

Though, what happens if I click the sign, leave the arena and re-enter it in less than 3 seconds? When I exit, puff, the inventory is gone; that's because when I leave the first time I have no items (as the custom class is "loading") and when I re-enter it, the server thinks my inventory is actually empty.

I use the specialjoin module, ofc. Also put the fixinventoryloss, yet... nothing

**Comment by slipcor** [comment]
The fixinventoryloss HAS to work on that, because it will not let you join with empty inventory - granted, choosing "custom" makes no sense then - but - well I am not fixing this because changing how this works can cause inventory loss for people who don't do weird things like this.

Inventories are really really hard to do right, and I do my best to support all kinds of plugins that fiddle with inventories when changing worlds, teleporting, leaving areas, entering areas - and so this waiting time is a must so everyone has a time to react and prepare the player to be cleared of their stuff

**Comment by Zughy** [comment]
The fact is, users can do be tard. And I'm 100% sure this will happen sooner or later. Being an RPG server, how can I explain to each one of them that: "Hey, you shouldn't go so fast!"? There will always be someone who doesn't listen or read, not for nothing a huge slice of developers' role is, basically, to prevent this kind of tardness. To build a bulletproof code (I'm a dev too, I'm not talking by hearsay). I can do some workaround via Denizen but it'd be cool, like, if I click a custom sign, I must wait 4 secs before leaving
