### ISSUE TITLE
[Feature] Disable God mode 

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#80]
Hi, 

Can you add option (/pa <name> set god on/off) to enable/disable god mode when player enter in arena plz ?

I use essentials and worldedit (but i think it's essentials command)

Thanks a lot

**Comment by slipcor** [comment]
no, but you can add a module that runs commands :)

Use the EventActions module and add this line:

pcmd<=>god off

in that case "god off" would be the command a player does

There is no way I can do a specific thing because I would have to add all possible god plugins, this way it can be generic and you enter your plugin's commands :D

**Comment by Oruss7** [comment]
Yes,  i had found this myself, sorry, i close this issue ^^'
